### ISSUE TITLE
"Clutter"

### ISSUE THREAD

**Issue by stevenwalton** [alihassanijr/.dotz#1]
I'm finally looking deeper at your version. When looking at your vim files I noticed a section for plugins in the [main file](https://github.com/alihassanijr/.dotfiles/blob/main/vimrc#L108). I just wanted to notice that this was the philosophy of my [vim/custom/plugins.vim](https://github.com/stevenwalton/.dotfiles/blob/master/vim/custom/plugins.vim) file. I found that this could really reduce the clutter and make issues easier to find and edit. Obviously could be expanded with `custom/plugins/plugin{1,2,3,...}.vim` if it grew large but I try to keep "simple." (Like the kitty and/or latex stuff could probably have their own files)

Good stuff though. I'll be pulling some of the things into mine (eventually I'll push lol)

You can close the issue btw

**Comment by alihassanijr** [comment]
Thanks for the comments.

Yeah I am way behind in cleaning stuff up. You think my vimrc is bad, check out `install.sh` lol.
